
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 33;
  public static final int LPAREN = 30;
  public static final int INT = 8;
  public static final int MINUS = 25;
  public static final int STATIC = 15;
  public static final int RPAREN = 31;
  public static final int NOT = 29;
  public static final int SEMICOLON = 32;
  public static final int AND = 23;
  public static final int LTHAN = 24;
  public static final int BOOL = 9;
  public static final int COMMA = 27;
  public static final int CLASS = 18;
  public static final int DIGIT = 39;
  public static final int PLUS = 21;
  public static final int MAIN = 17;
  public static final int IF = 3;
  public static final int THIS = 12;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 2;
  public static final int RBRACKET = 34;
  public static final int TRUE = 10;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int BECOMES = 22;
  public static final int VOID = 16;
  public static final int TIMES = 26;
  public static final int LBRACE = 35;
  public static final int ELSE = 4;
  public static final int WHILE = 5;
  public static final int PUBLIC = 14;
  public static final int RBRACE = 36;
  public static final int EXTENDS = 19;
  public static final int STRING = 7;
  public static final int TEXT = 37;
  public static final int FALSE = 11;
  public static final int LENGTH = 20;
  public static final int IDENTIFIER = 38;
  public static final int STDOUT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "STDOUT",
  "STRING",
  "INT",
  "BOOL",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "CLASS",
  "EXTENDS",
  "LENGTH",
  "PLUS",
  "BECOMES",
  "AND",
  "LTHAN",
  "MINUS",
  "TIMES",
  "COMMA",
  "DOT",
  "NOT",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "TEXT",
  "IDENTIFIER",
  "DIGIT"
  };
}

